### PR TITLE
Slack vitess 9 2021.05.24r9

### PR DESCRIPTION
**Pull request by ajm188**
## Description

cherry-picks https://github.com/vitessio/vitess/pull/8428

generated via `git cherry-pick d27354c^..d6fb25d`

## Related Issue(s)

- 

## Checklist
- [ ] Should this PR be backported?
- [ ] Tests were added or are not required
- [ ] Documentation was added or is not required

## Impacted Areas in Vitess
Components that this PR will affect:

- [ ]  Query Serving
- [ ]  VReplication
- [ ]  Cluster Management
- [ ]  Build

### CODE REVIEW

**Review by demmer — APPROVED** [review]
Code looks great!
I couldn't have written it better myself :)

**Comment by systay** [comment]
TIL how to cherry pick multiple commits. :smile:

**Review by guidoiaquinti — APPROVED** [review]

**Comment by ajm188** [comment]
closing and reopening with a different branch because i messed up my numbering 🤦

**Comment by ajm188** [comment]
https://github.com/tinyspeck/vitess/pull/227

**Pull request closed without merging**
