### PR TITLE
slack vitess update 10.02.2017

### PR DESCRIPTION
**Pull request by demmer**
Branch to sync with upstream and then apply three slack-specific patches onto the `slack-new-master` branch:

d09dcd9  redact out the /txlogz endpoint completely
9114772 redact out the /debug/consolidations UI
360abe9  redact bind variables and the full sql from /debug/querylog

Once this is merged I will force push to master.

### CODE REVIEW

**Comment by rafael** [comment]
LGTM

**Comment by rafael** [comment]
oh - it looks like we forgot to cherry pick this: 360abe9

**Comment by demmer** [comment]
@rafael No -- I actually updated the change with a fix to the unit test: https://github.com/tinyspeck/vitess/pull/40/commits/1dec806bfea3c9b99215893dfdab2ebdb9830ebd

**Comment by demmer** [comment]
I updated the PR description accordingly.

**Comment by rafael** [comment]
👍

**Pull request merged**
